file(READ "${INPUT}" shader HEX)
string(LENGTH "${shader}" length)
math(EXPR remainder "${length} % 8")
if(NOT remainder EQUAL 0 OR length LESS 40)
  message(FATAL_ERROR "Invalid helper SPIR-V length")
endif()
string(REGEX MATCHALL "........" words "${shader}")
if(NOT DEFINED NAME)
  set(NAME depth_resolve_shader)
endif()
set(text "#pragma once\n#include <cstdint>\nnamespace superman_returns::graphics::vulkan {\ninline constexpr uint32_t ${NAME}[]={\n")
foreach(word IN LISTS words)
  string(SUBSTRING "${word}" 0 2 b0)
  string(SUBSTRING "${word}" 2 2 b1)
  string(SUBSTRING "${word}" 4 2 b2)
  string(SUBSTRING "${word}" 6 2 b3)
  string(APPEND text "0x${b3}${b2}${b1}${b0}u,\n")
endforeach()
string(APPEND text "};\n}\n")
file(WRITE "${OUTPUT}" "${text}")
