"""Generates port/src/native_renderer/projection_regs.inc from the shader
catalog: the PS float-constant register holding the game's inverse
view-projection (4 rows) for every pixel shader that declares it. The native
renderer reads the current camera from those constants (SSAO, soft particles).
Conan's constant was g_mProjectionToWorld; Superman Returns' is unknown: find
it in artifacts/shaders/catalog.json and record it in game_profile.h
(kInverseViewProjectionName).
usage: python tools/shaders/gen_projection_regs.py --name <constant>

Ported from crazyriddler/rexglue-native-kit @136bc6c4, tools/shaders/gen_projection_regs.py
(constant name made a parameter, paths from srpaths.py)."""
import argparse
import json
import os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from srpaths import ARTIFACTS, NATIVE_SRC  # noqa: E402

ap = argparse.ArgumentParser()
ap.add_argument('--name', required=True, help="inverse view-projection constant name")
args = ap.parse_args()
catalog = json.load(open(ARTIFACTS / 'catalog.json'))['shaders']
rows = []
for e in catalog:
    if e['type'] != 'ps':
        continue
    for k in e['reflection'].get('constants', []):
        if k['name'] == args.name and k['rows'] == 4 and k['cols'] == 4:
            rows.append((int(e['container_hash'], 16), k['reg']))
rows.sort()
out = os.path.join(NATIVE_SRC, 'projection_regs.inc')
with open(out, 'w', newline='\n') as f:
    f.write('// Generated by tools/shaders/gen_projection_regs.py - do not edit.\n')
    f.write(f'// {{pixel shader hash, PS constant register of {args.name}}}\n')
    for h, reg in rows:
        f.write(f'{{0x{h:016X}ull, {reg}}},\n')
print(f'{len(rows)} shaders -> {out}')
