#include "test_main.h"
#include "policy.h"
using namespace superman_returns::graphics::vulkan;
static DeviceCandidate Gpu(std::string uuid="a") { return {"test",uuid,VK_API_VERSION_1_1,VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU,true,{{VK_QUEUE_GRAPHICS_BIT,true}}}; }
SR_TEST(device_selection_rejects_missing_uuid) { std::vector devices{Gpu()}; SR_CHECK(!SelectDevice(devices,"b").index); }
SR_TEST(device_selection_rejects_api_1_0_and_missing_present) { auto g=Gpu(); g.api_version=VK_API_VERSION_1_0; std::vector devices{g}; SR_CHECK(!SelectDevice(devices,"").index); devices[0]=Gpu(); devices[0].queues[0].present=false; SR_CHECK(!SelectDevice(devices,"").index); }
SR_TEST(device_selection_supports_split_queues) { auto g=Gpu(); g.queues={{VK_QUEUE_GRAPHICS_BIT,false},{0,true}}; std::vector devices{g}; auto r=SelectDevice(devices,""); SR_CHECK(r.index); SR_CHECK_EQ(r.graphics,0); SR_CHECK_EQ(r.present,1); }
SR_TEST(device_selection_prefers_discrete_when_auto) { auto d=Gpu("b"); d.type=VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU; std::vector devices{Gpu(),d}; SR_CHECK_EQ(*SelectDevice(devices,"").index,1); SR_CHECK_EQ(*SelectDevice(devices,"a").index,0); }
static VkSurfaceCapabilitiesKHR Caps() { VkSurfaceCapabilitiesKHR c{}; c.minImageCount=2;c.maxImageCount=0;c.currentExtent={UINT32_MAX,UINT32_MAX};c.minImageExtent={64,64};c.maxImageExtent={4096,4096};return c; }
SR_TEST(swapchain_choices_clamp_extent_and_count) { auto c=Caps(); std::vector<VkSurfaceFormatKHR> f{{VK_FORMAT_B8G8R8A8_UNORM,VK_COLOR_SPACE_SRGB_NONLINEAR_KHR}}; std::vector<VkPresentModeKHR> m{VK_PRESENT_MODE_FIFO_KHR};auto r=ChooseSwapchain(c,f,m,{16,8192},true); SR_CHECK(r);SR_CHECK_EQ(r->extent.width,64);SR_CHECK_EQ(r->extent.height,4096);SR_CHECK_EQ(r->count,3);c.maxImageCount=2;SR_CHECK_EQ(ChooseSwapchain(c,f,m,{1280,720},true)->count,2); }
SR_TEST(zero_extent_suspends_creation) { std::vector<VkSurfaceFormatKHR> f{{VK_FORMAT_UNDEFINED,VK_COLOR_SPACE_SRGB_NONLINEAR_KHR}};std::vector<VkPresentModeKHR> m{VK_PRESENT_MODE_FIFO_KHR};SR_CHECK(!ChooseSwapchain(Caps(),f,m,{0,0},true)); }
SR_TEST(fifo_is_used_for_vsync) { std::vector<VkSurfaceFormatKHR> f{{VK_FORMAT_UNDEFINED,VK_COLOR_SPACE_SRGB_NONLINEAR_KHR}};std::vector<VkPresentModeKHR> m{VK_PRESENT_MODE_MAILBOX_KHR,VK_PRESENT_MODE_FIFO_KHR};SR_CHECK_EQ(ChooseSwapchain(Caps(),f,m,{1280,720},true)->present_mode,VK_PRESENT_MODE_FIFO_KHR);SR_CHECK_EQ(ChooseSwapchain(Caps(),f,m,{1280,720},false)->present_mode,VK_PRESENT_MODE_MAILBOX_KHR); }
SR_TEST(memory_requires_host_visible) { std::vector<VkMemoryPropertyFlags> p{VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT};SR_CHECK_EQ(*ChooseMemoryType(7,p,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT,VK_MEMORY_PROPERTY_HOST_COHERENT_BIT),2);SR_CHECK(!ChooseMemoryType(1,p,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT,0)); }
SR_TEST(noncoherent_flush_is_atom_aligned_and_bounded) { auto r=AlignFlushRange(3,5,64,4);SR_CHECK(r.valid);SR_CHECK_EQ(r.offset,0);SR_CHECK_EQ(r.size,8);SR_CHECK(!AlignFlushRange(60,8,64,4).valid);r=AlignFlushRange(61,2,63,4);SR_CHECK(r.valid);SR_CHECK_EQ(r.offset,60);SR_CHECK_EQ(r.size,3); }
